name: Publish

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository == 'SimY4/SimY4'

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.139.0"
      - name: ⚙️ Build
        run: hugo --minify
