name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository == 'SimY4/SimY4'
      && !contains(toJSON(github.event.commits.*.message), '[skip]')

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
      - name: Build
        run: hugo
